export enum UserGender {
  MALE = 'male',
  FEMALE = 'female',
}

export enum UserRoles {
  TUTOR = 1,
  STUDENT = 2,
}

export enum EducationLevel {
  WO = 'WO',
  HBO = 'HBO',
  MBO = 'MBO',
  GYMNASIUM = 'Gymnasium',
  VWO = 'VWO',
  HAVO = 'HAVO',
  VMBO = 'VMBO',
}

export enum AccountStatus {
  ACTIVE = 'active',
  INACTIVE = 'inactive',
  PENDING = 'pending',
}

export enum Subjects {
  MATH = 'Wiskunde',
  ENGLISH = 'Engels',
  PHYSICS = 'Natuurkunde',
  CHEMISTRY = 'Scheikunde',
  BIOLOGY = 'Biologie',
  HISTORY = 'Geschiedenis',
  GEOGRAPHY = 'Aardrijkskunde',
  PHILOSOPHY = 'Filosofie',
  FRENCH = 'Frans',
  GERMAN = 'Duits',
  SPANISH = 'Spaans',
  ITALIAN = 'Italiaans',
  CHINESE = 'Chinees',
  RUSSIAN = 'Rusisch',
  DUTCH = 'Nederlands',
  JAPANESE = 'Japans',
  KOREAN = 'Koreaans',
  ARABIC = 'Arabisch',
  LATIN = 'Latijn',
  GREEK = 'Grieks',
  MUSIC = 'Muziek',
  ART = 'Kunst',
  SPORT = 'Sport',
  ANTHROPOLOGY = 'Antropologie',
  LITERATURE = 'Literatuur',
  POLITICS = 'Politiek',
  CULTURE = 'Cultuur',
  PSYCHOLOGY = 'Psychologie',
  RELIGION = 'Religie',
  SOCIOLOGY = 'Sociologie',
  THEATRE = 'Theater',
  BUSINESS = 'Bedrijfskunde',
  ACCOUNTING = 'Boekhouding',
  FINANCE = 'Financieel',
  MARKETING = 'Marketing',
  HR = 'HR',
  ECONOMICS = 'Economie',
  ENGINEERING = 'Ingenieurswetenschap',
  COMPUTER_SCIENCE = 'Informatica',
  ARCHITECTURE = 'Architectuur',
  MEDICINE = 'Geneeskunde',
  VETERINARY = 'Diergeneeskunde',
  NURSING = 'Verpleegkunde',
  LAW = 'Rechten',
  PHARMACY = 'Apotheek',
  ENVIRONMENT = 'Milieu',
  AGRICULTURE = 'Landbouw',
  ANIMAL_SCIENCE = 'Dierwetenschap',
  FOOD_SCIENCE = 'Voedingswetenschap',
  NUTRITION = 'Voeding',
  SOCIAL_WORK = 'Maatschappelijk werk',
  TEACHING = 'Onderwijzen',
  OTHER = 'Anders',
}
